### PR TITLE
New icons and better fit UI

### PR DESCRIPTION
**Pull request by King-Wally**
I changed the icons to the ones used in Renderman for Maya and placed them in the plugintoolbar
This may break compatibility with versions prior to 2018.1.0
untitled-1 2x

### CODE REVIEW

**Comment by pleprince** [comment]
That's looking great, Thanks ! 
Ideally, I would like to keep compatibility with older versions. Could you amend your pull request to keep the old UI for older versions ? I imagine you could use `alg.version.painter` to choose between the old code and the new one in `main.qml` ?

**Comment by King-Wally** [comment]
Would you like to keep the old icons with older versions of painter or could I change them to the new ones?

**Comment by pleprince** [comment]
Use the new ones if you prefer them ;-)

--
Philippe

**Comment by King-Wally** [comment]
Done!
schermafbeelding 2018-11-26 om 21 25 04

**Pull request merged**
